/**
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine.myDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.behavior.withstatemachine.myDSL.Event#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.behavior.withstatemachine.myDSL.Event#getEvenrates <em>Evenrates</em>}</li>
 * </ul>
 *
 * @see org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage#getEvent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.behavior.withstatemachine.myDSL.Event#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Evenrates</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.behavior.withstatemachine.myDSL.Rate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evenrates</em>' containment reference list.
   * @see org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage#getEvent_Evenrates()
   * @model containment="true"
   * @generated
   */
  EList<Rate> getEvenrates();

} // Event
