/**
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine.myDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.behavior.withstatemachine.myDSL.Rate#getEventval <em>Eventval</em>}</li>
 * </ul>
 *
 * @see org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage#getRate()
 * @model
 * @generated
 */
public interface Rate extends EObject
{
  /**
   * Returns the value of the '<em><b>Eventval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eventval</em>' attribute.
   * @see #setEventval(int)
   * @see org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage#getRate_Eventval()
   * @model
   * @generated
   */
  int getEventval();

  /**
   * Sets the value of the '{@link org.xtext.behavior.withstatemachine.myDSL.Rate#getEventval <em>Eventval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eventval</em>' attribute.
   * @see #getEventval()
   * @generated
   */
  void setEventval(int value);

} // Rate
