/**
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine.myDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transitions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.behavior.withstatemachine.myDSL.Transitions#getEvent <em>Event</em>}</li>
 *   <li>{@link org.xtext.behavior.withstatemachine.myDSL.Transitions#getEventrates <em>Eventrates</em>}</li>
 *   <li>{@link org.xtext.behavior.withstatemachine.myDSL.Transitions#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage#getTransitions()
 * @model
 * @generated
 */
public interface Transitions extends EObject
{
  /**
   * Returns the value of the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' reference.
   * @see #setEvent(Event)
   * @see org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage#getTransitions_Event()
   * @model
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link org.xtext.behavior.withstatemachine.myDSL.Transitions#getEvent <em>Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

  /**
   * Returns the value of the '<em><b>Eventrates</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eventrates</em>' reference.
   * @see #setEventrates(Rate)
   * @see org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage#getTransitions_Eventrates()
   * @model
   * @generated
   */
  Rate getEventrates();

  /**
   * Sets the value of the '{@link org.xtext.behavior.withstatemachine.myDSL.Transitions#getEventrates <em>Eventrates</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eventrates</em>' reference.
   * @see #getEventrates()
   * @generated
   */
  void setEventrates(Rate value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(State)
   * @see org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage#getTransitions_Target()
   * @model
   * @generated
   */
  State getTarget();

  /**
   * Sets the value of the '{@link org.xtext.behavior.withstatemachine.myDSL.Transitions#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(State value);

} // Transitions
