/*
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/behavior/withstatemachine/parser/antlr/internal/InternalMyDSL.tokens");
	}
}
