/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Askfordata</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage#getAskfordata()
 * @model
 * @generated
 */
public interface Askfordata extends Datatoinfer
{
} // Askfordata
