/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.sosarch.csdesign.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/sosarch/csdesign/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.ConstiuteintsystemDesignImpl <em>Constiuteintsystem Design</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.ConstiuteintsystemDesignImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getConstiuteintsystemDesign()
   * @generated
   */
  int CONSTIUTEINTSYSTEM_DESIGN = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTIUTEINTSYSTEM_DESIGN__ACTIONS = 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTIUTEINTSYSTEM_DESIGN__ACTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTIUTEINTSYSTEM_DESIGN__NAME = 2;

  /**
   * The feature id for the '<em><b>Ports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTIUTEINTSYSTEM_DESIGN__PORTS = 3;

  /**
   * The number of structural features of the '<em>Constiuteintsystem Design</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTIUTEINTSYSTEM_DESIGN_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.PortImpl <em>Port</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.PortImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getPort()
   * @generated
   */
  int PORT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__NAME = 0;

  /**
   * The feature id for the '<em><b>Provides</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__PROVIDES = 1;

  /**
   * The feature id for the '<em><b>Requires</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__REQUIRES = 2;

  /**
   * The number of structural features of the '<em>Port</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.StochasticbehaviorImpl <em>Stochasticbehavior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.StochasticbehaviorImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getStochasticbehavior()
   * @generated
   */
  int STOCHASTICBEHAVIOR = 2;

  /**
   * The number of structural features of the '<em>Stochasticbehavior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHASTICBEHAVIOR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.StochaticConstriantsImpl <em>Stochatic Constriants</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.StochaticConstriantsImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getStochaticConstriants()
   * @generated
   */
  int STOCHATIC_CONSTRIANTS = 3;

  /**
   * The feature id for the '<em><b>Constraint Share Date</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHATIC_CONSTRIANTS__CONSTRAINT_SHARE_DATE = 0;

  /**
   * The feature id for the '<em><b>Rate</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHATIC_CONSTRIANTS__RATE = 1;

  /**
   * The feature id for the '<em><b>Constraint Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHATIC_CONSTRIANTS__CONSTRAINT_DATA = 2;

  /**
   * The number of structural features of the '<em>Stochatic Constriants</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHATIC_CONSTRIANTS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.DatatoinferImpl <em>Datatoinfer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.DatatoinferImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getDatatoinfer()
   * @generated
   */
  int DATATOINFER = 4;

  /**
   * The number of structural features of the '<em>Datatoinfer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATOINFER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.shardataImpl <em>shardata</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.shardataImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getshardata()
   * @generated
   */
  int SHARDATA = 5;

  /**
   * The number of structural features of the '<em>shardata</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHARDATA_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.SystemTranstionsImpl <em>System Transtions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.SystemTranstionsImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getSystemTranstions()
   * @generated
   */
  int SYSTEM_TRANSTIONS = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TRANSTIONS__NAME = 0;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TRANSTIONS__STATES = 1;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TRANSTIONS__EVENTS = 2;

  /**
   * The number of structural features of the '<em>System Transtions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TRANSTIONS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.StateImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getState()
   * @generated
   */
  int STATE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__TRANSITIONS = 1;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.TransitionImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 8;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__EVENT = 0;

  /**
   * The feature id for the '<em><b>Rate</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__RATE = 1;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TARGET = 2;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.OperationImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 9;

  /**
   * The feature id for the '<em><b>Recieves</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__RECIEVES = 0;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.ratesImpl <em>rates</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.ratesImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getrates()
   * @generated
   */
  int RATES = 10;

  /**
   * The feature id for the '<em><b>Rates</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATES__RATES = 0;

  /**
   * The number of structural features of the '<em>rates</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.EventImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Operation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__OPERATION = 1;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.requireImpl <em>require</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.requireImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getrequire()
   * @generated
   */
  int REQUIRE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRE__NAME = 0;

  /**
   * The number of structural features of the '<em>require</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.provideImpl <em>provide</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.provideImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getprovide()
   * @generated
   */
  int PROVIDE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROVIDE__NAME = 0;

  /**
   * The number of structural features of the '<em>provide</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROVIDE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.StochaticBehaviorImpl <em>Stochatic Behavior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.StochaticBehaviorImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getStochaticBehavior()
   * @generated
   */
  int STOCHATIC_BEHAVIOR = 14;

  /**
   * The feature id for the '<em><b>System Transition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHATIC_BEHAVIOR__SYSTEM_TRANSITION = STOCHASTICBEHAVIOR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Con Constraint</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHATIC_BEHAVIOR__CON_CONSTRAINT = STOCHASTICBEHAVIOR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Stochatic Behavior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHATIC_BEHAVIOR_FEATURE_COUNT = STOCHASTICBEHAVIOR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.AskfordataImpl <em>Askfordata</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.AskfordataImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getAskfordata()
   * @generated
   */
  int ASKFORDATA = 15;

  /**
   * The number of structural features of the '<em>Askfordata</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASKFORDATA_FEATURE_COUNT = DATATOINFER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.TellDataImpl <em>Tell Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.TellDataImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getTellData()
   * @generated
   */
  int TELL_DATA = 16;

  /**
   * The number of structural features of the '<em>Tell Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TELL_DATA_FEATURE_COUNT = SHARDATA_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.operationsImpl <em>operations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sosarch.csdesign.myDsl.impl.operationsImpl
   * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getoperations()
   * @generated
   */
  int OPERATIONS = 17;

  /**
   * The feature id for the '<em><b>Recieves</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIONS__RECIEVES = OPERATION__RECIEVES;

  /**
   * The feature id for the '<em><b>Sends</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIONS__SENDS = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>operations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIONS_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign <em>Constiuteintsystem Design</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constiuteintsystem Design</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign
   * @generated
   */
  EClass getConstiuteintsystemDesign();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign#getActions()
   * @see #getConstiuteintsystemDesign()
   * @generated
   */
  EReference getConstiuteintsystemDesign_Actions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign#getAction()
   * @see #getConstiuteintsystemDesign()
   * @generated
   */
  EReference getConstiuteintsystemDesign_Action();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign#getName()
   * @see #getConstiuteintsystemDesign()
   * @generated
   */
  EAttribute getConstiuteintsystemDesign_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign#getPorts <em>Ports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ports</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign#getPorts()
   * @see #getConstiuteintsystemDesign()
   * @generated
   */
  EReference getConstiuteintsystemDesign_Ports();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.Port <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Port
   * @generated
   */
  EClass getPort();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sosarch.csdesign.myDsl.Port#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Port#getName()
   * @see #getPort()
   * @generated
   */
  EAttribute getPort_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.Port#getProvides <em>Provides</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Provides</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Port#getProvides()
   * @see #getPort()
   * @generated
   */
  EReference getPort_Provides();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.Port#getRequires <em>Requires</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Requires</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Port#getRequires()
   * @see #getPort()
   * @generated
   */
  EReference getPort_Requires();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.Stochasticbehavior <em>Stochasticbehavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stochasticbehavior</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Stochasticbehavior
   * @generated
   */
  EClass getStochasticbehavior();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.StochaticConstriants <em>Stochatic Constriants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stochatic Constriants</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.StochaticConstriants
   * @generated
   */
  EClass getStochaticConstriants();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.StochaticConstriants#getConstraintShareDate <em>Constraint Share Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraint Share Date</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.StochaticConstriants#getConstraintShareDate()
   * @see #getStochaticConstriants()
   * @generated
   */
  EReference getStochaticConstriants_ConstraintShareDate();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.StochaticConstriants#getRate <em>Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rate</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.StochaticConstriants#getRate()
   * @see #getStochaticConstriants()
   * @generated
   */
  EReference getStochaticConstriants_Rate();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.StochaticConstriants#getConstraintData <em>Constraint Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraint Data</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.StochaticConstriants#getConstraintData()
   * @see #getStochaticConstriants()
   * @generated
   */
  EReference getStochaticConstriants_ConstraintData();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.Datatoinfer <em>Datatoinfer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datatoinfer</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Datatoinfer
   * @generated
   */
  EClass getDatatoinfer();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.shardata <em>shardata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>shardata</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.shardata
   * @generated
   */
  EClass getshardata();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.SystemTranstions <em>System Transtions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Transtions</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.SystemTranstions
   * @generated
   */
  EClass getSystemTranstions();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sosarch.csdesign.myDsl.SystemTranstions#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.SystemTranstions#getName()
   * @see #getSystemTranstions()
   * @generated
   */
  EAttribute getSystemTranstions_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.SystemTranstions#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.SystemTranstions#getStates()
   * @see #getSystemTranstions()
   * @generated
   */
  EReference getSystemTranstions_States();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.SystemTranstions#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.SystemTranstions#getEvents()
   * @see #getSystemTranstions()
   * @generated
   */
  EReference getSystemTranstions_Events();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sosarch.csdesign.myDsl.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.State#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.State#getTransitions()
   * @see #getState()
   * @generated
   */
  EReference getState_Transitions();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sosarch.csdesign.myDsl.Transition#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Transition#getEvent()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Event();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sosarch.csdesign.myDsl.Transition#getRate <em>Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Rate</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Transition#getRate()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Rate();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sosarch.csdesign.myDsl.Transition#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Transition#getTarget()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.sosarch.csdesign.myDsl.Operation#getRecieves <em>Recieves</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Recieves</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Operation#getRecieves()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Recieves();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.rates <em>rates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>rates</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.rates
   * @generated
   */
  EClass getrates();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sosarch.csdesign.myDsl.rates#getRates <em>Rates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rates</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.rates#getRates()
   * @see #getrates()
   * @generated
   */
  EAttribute getrates_Rates();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sosarch.csdesign.myDsl.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sosarch.csdesign.myDsl.Event#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Operation</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Event#getOperation()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Operation();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.require <em>require</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>require</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.require
   * @generated
   */
  EClass getrequire();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sosarch.csdesign.myDsl.require#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.require#getName()
   * @see #getrequire()
   * @generated
   */
  EAttribute getrequire_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.provide <em>provide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>provide</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.provide
   * @generated
   */
  EClass getprovide();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sosarch.csdesign.myDsl.provide#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.provide#getName()
   * @see #getprovide()
   * @generated
   */
  EAttribute getprovide_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.StochaticBehavior <em>Stochatic Behavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stochatic Behavior</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.StochaticBehavior
   * @generated
   */
  EClass getStochaticBehavior();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.StochaticBehavior#getSystemTransition <em>System Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>System Transition</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.StochaticBehavior#getSystemTransition()
   * @see #getStochaticBehavior()
   * @generated
   */
  EReference getStochaticBehavior_SystemTransition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sosarch.csdesign.myDsl.StochaticBehavior#getConConstraint <em>Con Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Con Constraint</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.StochaticBehavior#getConConstraint()
   * @see #getStochaticBehavior()
   * @generated
   */
  EReference getStochaticBehavior_ConConstraint();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.Askfordata <em>Askfordata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Askfordata</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.Askfordata
   * @generated
   */
  EClass getAskfordata();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.TellData <em>Tell Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tell Data</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.TellData
   * @generated
   */
  EClass getTellData();

  /**
   * Returns the meta object for class '{@link org.xtext.sosarch.csdesign.myDsl.operations <em>operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>operations</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.operations
   * @generated
   */
  EClass getoperations();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.sosarch.csdesign.myDsl.operations#getSends <em>Sends</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Sends</em>'.
   * @see org.xtext.sosarch.csdesign.myDsl.operations#getSends()
   * @see #getoperations()
   * @generated
   */
  EAttribute getoperations_Sends();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.ConstiuteintsystemDesignImpl <em>Constiuteintsystem Design</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.ConstiuteintsystemDesignImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getConstiuteintsystemDesign()
     * @generated
     */
    EClass CONSTIUTEINTSYSTEM_DESIGN = eINSTANCE.getConstiuteintsystemDesign();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTIUTEINTSYSTEM_DESIGN__ACTIONS = eINSTANCE.getConstiuteintsystemDesign_Actions();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTIUTEINTSYSTEM_DESIGN__ACTION = eINSTANCE.getConstiuteintsystemDesign_Action();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTIUTEINTSYSTEM_DESIGN__NAME = eINSTANCE.getConstiuteintsystemDesign_Name();

    /**
     * The meta object literal for the '<em><b>Ports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTIUTEINTSYSTEM_DESIGN__PORTS = eINSTANCE.getConstiuteintsystemDesign_Ports();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.PortImpl <em>Port</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.PortImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getPort()
     * @generated
     */
    EClass PORT = eINSTANCE.getPort();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORT__NAME = eINSTANCE.getPort_Name();

    /**
     * The meta object literal for the '<em><b>Provides</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORT__PROVIDES = eINSTANCE.getPort_Provides();

    /**
     * The meta object literal for the '<em><b>Requires</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORT__REQUIRES = eINSTANCE.getPort_Requires();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.StochasticbehaviorImpl <em>Stochasticbehavior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.StochasticbehaviorImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getStochasticbehavior()
     * @generated
     */
    EClass STOCHASTICBEHAVIOR = eINSTANCE.getStochasticbehavior();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.StochaticConstriantsImpl <em>Stochatic Constriants</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.StochaticConstriantsImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getStochaticConstriants()
     * @generated
     */
    EClass STOCHATIC_CONSTRIANTS = eINSTANCE.getStochaticConstriants();

    /**
     * The meta object literal for the '<em><b>Constraint Share Date</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STOCHATIC_CONSTRIANTS__CONSTRAINT_SHARE_DATE = eINSTANCE.getStochaticConstriants_ConstraintShareDate();

    /**
     * The meta object literal for the '<em><b>Rate</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STOCHATIC_CONSTRIANTS__RATE = eINSTANCE.getStochaticConstriants_Rate();

    /**
     * The meta object literal for the '<em><b>Constraint Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STOCHATIC_CONSTRIANTS__CONSTRAINT_DATA = eINSTANCE.getStochaticConstriants_ConstraintData();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.DatatoinferImpl <em>Datatoinfer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.DatatoinferImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getDatatoinfer()
     * @generated
     */
    EClass DATATOINFER = eINSTANCE.getDatatoinfer();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.shardataImpl <em>shardata</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.shardataImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getshardata()
     * @generated
     */
    EClass SHARDATA = eINSTANCE.getshardata();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.SystemTranstionsImpl <em>System Transtions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.SystemTranstionsImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getSystemTranstions()
     * @generated
     */
    EClass SYSTEM_TRANSTIONS = eINSTANCE.getSystemTranstions();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_TRANSTIONS__NAME = eINSTANCE.getSystemTranstions_Name();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_TRANSTIONS__STATES = eINSTANCE.getSystemTranstions_States();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_TRANSTIONS__EVENTS = eINSTANCE.getSystemTranstions_Events();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.StateImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__TRANSITIONS = eINSTANCE.getState_Transitions();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.TransitionImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__EVENT = eINSTANCE.getTransition_Event();

    /**
     * The meta object literal for the '<em><b>Rate</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__RATE = eINSTANCE.getTransition_Rate();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TARGET = eINSTANCE.getTransition_Target();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.OperationImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Recieves</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__RECIEVES = eINSTANCE.getOperation_Recieves();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.ratesImpl <em>rates</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.ratesImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getrates()
     * @generated
     */
    EClass RATES = eINSTANCE.getrates();

    /**
     * The meta object literal for the '<em><b>Rates</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RATES__RATES = eINSTANCE.getrates_Rates();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.EventImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__OPERATION = eINSTANCE.getEvent_Operation();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.requireImpl <em>require</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.requireImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getrequire()
     * @generated
     */
    EClass REQUIRE = eINSTANCE.getrequire();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REQUIRE__NAME = eINSTANCE.getrequire_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.provideImpl <em>provide</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.provideImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getprovide()
     * @generated
     */
    EClass PROVIDE = eINSTANCE.getprovide();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROVIDE__NAME = eINSTANCE.getprovide_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.StochaticBehaviorImpl <em>Stochatic Behavior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.StochaticBehaviorImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getStochaticBehavior()
     * @generated
     */
    EClass STOCHATIC_BEHAVIOR = eINSTANCE.getStochaticBehavior();

    /**
     * The meta object literal for the '<em><b>System Transition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STOCHATIC_BEHAVIOR__SYSTEM_TRANSITION = eINSTANCE.getStochaticBehavior_SystemTransition();

    /**
     * The meta object literal for the '<em><b>Con Constraint</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STOCHATIC_BEHAVIOR__CON_CONSTRAINT = eINSTANCE.getStochaticBehavior_ConConstraint();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.AskfordataImpl <em>Askfordata</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.AskfordataImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getAskfordata()
     * @generated
     */
    EClass ASKFORDATA = eINSTANCE.getAskfordata();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.TellDataImpl <em>Tell Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.TellDataImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getTellData()
     * @generated
     */
    EClass TELL_DATA = eINSTANCE.getTellData();

    /**
     * The meta object literal for the '{@link org.xtext.sosarch.csdesign.myDsl.impl.operationsImpl <em>operations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sosarch.csdesign.myDsl.impl.operationsImpl
     * @see org.xtext.sosarch.csdesign.myDsl.impl.MyDslPackageImpl#getoperations()
     * @generated
     */
    EClass OPERATIONS = eINSTANCE.getoperations();

    /**
     * The meta object literal for the '<em><b>Sends</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATIONS__SENDS = eINSTANCE.getoperations_Sends();

  }

} //MyDslPackage
