/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = org.xtext.sosarch.csdesign.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Constiuteintsystem Design</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constiuteintsystem Design</em>'.
   * @generated
   */
  ConstiuteintsystemDesign createConstiuteintsystemDesign();

  /**
   * Returns a new object of class '<em>Port</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Port</em>'.
   * @generated
   */
  Port createPort();

  /**
   * Returns a new object of class '<em>Stochasticbehavior</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stochasticbehavior</em>'.
   * @generated
   */
  Stochasticbehavior createStochasticbehavior();

  /**
   * Returns a new object of class '<em>Stochatic Constriants</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stochatic Constriants</em>'.
   * @generated
   */
  StochaticConstriants createStochaticConstriants();

  /**
   * Returns a new object of class '<em>Datatoinfer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Datatoinfer</em>'.
   * @generated
   */
  Datatoinfer createDatatoinfer();

  /**
   * Returns a new object of class '<em>shardata</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>shardata</em>'.
   * @generated
   */
  shardata createshardata();

  /**
   * Returns a new object of class '<em>System Transtions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System Transtions</em>'.
   * @generated
   */
  SystemTranstions createSystemTranstions();

  /**
   * Returns a new object of class '<em>State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State</em>'.
   * @generated
   */
  State createState();

  /**
   * Returns a new object of class '<em>Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transition</em>'.
   * @generated
   */
  Transition createTransition();

  /**
   * Returns a new object of class '<em>Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation</em>'.
   * @generated
   */
  Operation createOperation();

  /**
   * Returns a new object of class '<em>rates</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>rates</em>'.
   * @generated
   */
  rates createrates();

  /**
   * Returns a new object of class '<em>Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event</em>'.
   * @generated
   */
  Event createEvent();

  /**
   * Returns a new object of class '<em>require</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>require</em>'.
   * @generated
   */
  require createrequire();

  /**
   * Returns a new object of class '<em>provide</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>provide</em>'.
   * @generated
   */
  provide createprovide();

  /**
   * Returns a new object of class '<em>Stochatic Behavior</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stochatic Behavior</em>'.
   * @generated
   */
  StochaticBehavior createStochaticBehavior();

  /**
   * Returns a new object of class '<em>Askfordata</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Askfordata</em>'.
   * @generated
   */
  Askfordata createAskfordata();

  /**
   * Returns a new object of class '<em>Tell Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tell Data</em>'.
   * @generated
   */
  TellData createTellData();

  /**
   * Returns a new object of class '<em>operations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>operations</em>'.
   * @generated
   */
  operations createoperations();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
