/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>rates</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.rates#getRates <em>Rates</em>}</li>
 * </ul>
 *
 * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage#getrates()
 * @model
 * @generated
 */
public interface rates extends EObject
{
  /**
   * Returns the value of the '<em><b>Rates</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rates</em>' attribute.
   * @see #setRates(int)
   * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage#getrates_Rates()
   * @model
   * @generated
   */
  int getRates();

  /**
   * Sets the value of the '{@link org.xtext.sosarch.csdesign.myDsl.rates#getRates <em>Rates</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rates</em>' attribute.
   * @see #getRates()
   * @generated
   */
  void setRates(int value);

} // rates
