/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stochatic Constriants</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.StochaticConstriants#getConstraintShareDate <em>Constraint Share Date</em>}</li>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.StochaticConstriants#getRate <em>Rate</em>}</li>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.StochaticConstriants#getConstraintData <em>Constraint Data</em>}</li>
 * </ul>
 *
 * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage#getStochaticConstriants()
 * @model
 * @generated
 */
public interface StochaticConstriants extends EObject
{
  /**
   * Returns the value of the '<em><b>Constraint Share Date</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosarch.csdesign.myDsl.shardata}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint Share Date</em>' containment reference list.
   * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage#getStochaticConstriants_ConstraintShareDate()
   * @model containment="true"
   * @generated
   */
  EList<shardata> getConstraintShareDate();

  /**
   * Returns the value of the '<em><b>Rate</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosarch.csdesign.myDsl.rates}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rate</em>' containment reference list.
   * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage#getStochaticConstriants_Rate()
   * @model containment="true"
   * @generated
   */
  EList<rates> getRate();

  /**
   * Returns the value of the '<em><b>Constraint Data</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosarch.csdesign.myDsl.Datatoinfer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint Data</em>' containment reference list.
   * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage#getStochaticConstriants_ConstraintData()
   * @model containment="true"
   * @generated
   */
  EList<Datatoinfer> getConstraintData();

} // StochaticConstriants
