/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stochasticbehavior</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage#getStochasticbehavior()
 * @model
 * @generated
 */
public interface Stochasticbehavior extends EObject
{
} // Stochasticbehavior
