/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tell Data</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.sosarch.csdesign.myDsl.MyDslPackage#getTellData()
 * @model
 * @generated
 */
public interface TellData extends shardata
{
} // TellData
