/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.sosarch.csdesign.myDsl.Askfordata;
import org.xtext.sosarch.csdesign.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Askfordata</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AskfordataImpl extends DatatoinferImpl implements Askfordata
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AskfordataImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ASKFORDATA;
  }

} //AskfordataImpl
