/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.sosarch.csdesign.myDsl.ConstiuteintsystemDesign;
import org.xtext.sosarch.csdesign.myDsl.MyDslPackage;
import org.xtext.sosarch.csdesign.myDsl.Port;
import org.xtext.sosarch.csdesign.myDsl.rates;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constiuteintsystem Design</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.impl.ConstiuteintsystemDesignImpl#getActions <em>Actions</em>}</li>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.impl.ConstiuteintsystemDesignImpl#getAction <em>Action</em>}</li>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.impl.ConstiuteintsystemDesignImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.impl.ConstiuteintsystemDesignImpl#getPorts <em>Ports</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConstiuteintsystemDesignImpl extends MinimalEObjectImpl.Container implements ConstiuteintsystemDesign
{
  /**
   * The cached value of the '{@link #getActions() <em>Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActions()
   * @generated
   * @ordered
   */
  protected EList<rates> actions;

  /**
   * The cached value of the '{@link #getAction() <em>Action</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAction()
   * @generated
   * @ordered
   */
  protected EList<rates> action;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getPorts() <em>Ports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPorts()
   * @generated
   * @ordered
   */
  protected EList<Port> ports;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstiuteintsystemDesignImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.CONSTIUTEINTSYSTEM_DESIGN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<rates> getActions()
  {
    if (actions == null)
    {
      actions = new EObjectContainmentEList<rates>(rates.class, this, MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTIONS);
    }
    return actions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<rates> getAction()
  {
    if (action == null)
    {
      action = new EObjectContainmentEList<rates>(rates.class, this, MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTION);
    }
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Port> getPorts()
  {
    if (ports == null)
    {
      ports = new EObjectContainmentEList<Port>(Port.class, this, MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__PORTS);
    }
    return ports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTIONS:
        return ((InternalEList<?>)getActions()).basicRemove(otherEnd, msgs);
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTION:
        return ((InternalEList<?>)getAction()).basicRemove(otherEnd, msgs);
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__PORTS:
        return ((InternalEList<?>)getPorts()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTIONS:
        return getActions();
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTION:
        return getAction();
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__NAME:
        return getName();
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__PORTS:
        return getPorts();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTIONS:
        getActions().clear();
        getActions().addAll((Collection<? extends rates>)newValue);
        return;
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTION:
        getAction().clear();
        getAction().addAll((Collection<? extends rates>)newValue);
        return;
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__PORTS:
        getPorts().clear();
        getPorts().addAll((Collection<? extends Port>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTIONS:
        getActions().clear();
        return;
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTION:
        getAction().clear();
        return;
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__PORTS:
        getPorts().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTIONS:
        return actions != null && !actions.isEmpty();
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__ACTION:
        return action != null && !action.isEmpty();
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.CONSTIUTEINTSYSTEM_DESIGN__PORTS:
        return ports != null && !ports.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ConstiuteintsystemDesignImpl
