/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.sosarch.csdesign.myDsl.Datatoinfer;
import org.xtext.sosarch.csdesign.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Datatoinfer</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DatatoinferImpl extends MinimalEObjectImpl.Container implements Datatoinfer
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DatatoinferImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.DATATOINFER;
  }

} //DatatoinferImpl
