/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.sosarch.csdesign.myDsl.MyDslPackage;
import org.xtext.sosarch.csdesign.myDsl.StochaticBehavior;
import org.xtext.sosarch.csdesign.myDsl.StochaticConstriants;
import org.xtext.sosarch.csdesign.myDsl.SystemTranstions;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Stochatic Behavior</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.impl.StochaticBehaviorImpl#getSystemTransition <em>System Transition</em>}</li>
 *   <li>{@link org.xtext.sosarch.csdesign.myDsl.impl.StochaticBehaviorImpl#getConConstraint <em>Con Constraint</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StochaticBehaviorImpl extends StochasticbehaviorImpl implements StochaticBehavior
{
  /**
   * The cached value of the '{@link #getSystemTransition() <em>System Transition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSystemTransition()
   * @generated
   * @ordered
   */
  protected EList<SystemTranstions> systemTransition;

  /**
   * The cached value of the '{@link #getConConstraint() <em>Con Constraint</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConConstraint()
   * @generated
   * @ordered
   */
  protected EList<StochaticConstriants> conConstraint;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StochaticBehaviorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.STOCHATIC_BEHAVIOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SystemTranstions> getSystemTransition()
  {
    if (systemTransition == null)
    {
      systemTransition = new EObjectContainmentEList<SystemTranstions>(SystemTranstions.class, this, MyDslPackage.STOCHATIC_BEHAVIOR__SYSTEM_TRANSITION);
    }
    return systemTransition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StochaticConstriants> getConConstraint()
  {
    if (conConstraint == null)
    {
      conConstraint = new EObjectContainmentEList<StochaticConstriants>(StochaticConstriants.class, this, MyDslPackage.STOCHATIC_BEHAVIOR__CON_CONSTRAINT);
    }
    return conConstraint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.STOCHATIC_BEHAVIOR__SYSTEM_TRANSITION:
        return ((InternalEList<?>)getSystemTransition()).basicRemove(otherEnd, msgs);
      case MyDslPackage.STOCHATIC_BEHAVIOR__CON_CONSTRAINT:
        return ((InternalEList<?>)getConConstraint()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.STOCHATIC_BEHAVIOR__SYSTEM_TRANSITION:
        return getSystemTransition();
      case MyDslPackage.STOCHATIC_BEHAVIOR__CON_CONSTRAINT:
        return getConConstraint();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.STOCHATIC_BEHAVIOR__SYSTEM_TRANSITION:
        getSystemTransition().clear();
        getSystemTransition().addAll((Collection<? extends SystemTranstions>)newValue);
        return;
      case MyDslPackage.STOCHATIC_BEHAVIOR__CON_CONSTRAINT:
        getConConstraint().clear();
        getConConstraint().addAll((Collection<? extends StochaticConstriants>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.STOCHATIC_BEHAVIOR__SYSTEM_TRANSITION:
        getSystemTransition().clear();
        return;
      case MyDslPackage.STOCHATIC_BEHAVIOR__CON_CONSTRAINT:
        getConConstraint().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.STOCHATIC_BEHAVIOR__SYSTEM_TRANSITION:
        return systemTransition != null && !systemTransition.isEmpty();
      case MyDslPackage.STOCHATIC_BEHAVIOR__CON_CONSTRAINT:
        return conConstraint != null && !conConstraint.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //StochaticBehaviorImpl
