/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.sosarch.csdesign.myDsl.MyDslPackage;
import org.xtext.sosarch.csdesign.myDsl.TellData;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tell Data</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TellDataImpl extends shardataImpl implements TellData
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TellDataImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TELL_DATA;
  }

} //TellDataImpl
