/**
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine.myDSL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.behavior.withstatemachine.myDSL.Event;
import org.xtext.behavior.withstatemachine.myDSL.MyDSLPackage;
import org.xtext.behavior.withstatemachine.myDSL.Rate;
import org.xtext.behavior.withstatemachine.myDSL.State;
import org.xtext.behavior.withstatemachine.myDSL.Transitions;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transitions</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.behavior.withstatemachine.myDSL.impl.TransitionsImpl#getEvent <em>Event</em>}</li>
 *   <li>{@link org.xtext.behavior.withstatemachine.myDSL.impl.TransitionsImpl#getEventrates <em>Eventrates</em>}</li>
 *   <li>{@link org.xtext.behavior.withstatemachine.myDSL.impl.TransitionsImpl#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TransitionsImpl extends MinimalEObjectImpl.Container implements Transitions
{
  /**
   * The cached value of the '{@link #getEvent() <em>Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvent()
   * @generated
   * @ordered
   */
  protected Event event;

  /**
   * The cached value of the '{@link #getEventrates() <em>Eventrates</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEventrates()
   * @generated
   * @ordered
   */
  protected Rate eventrates;

  /**
   * The cached value of the '{@link #getTarget() <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected State target;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransitionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDSLPackage.Literals.TRANSITIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event getEvent()
  {
    if (event != null && event.eIsProxy())
    {
      InternalEObject oldEvent = (InternalEObject)event;
      event = (Event)eResolveProxy(oldEvent);
      if (event != oldEvent)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDSLPackage.TRANSITIONS__EVENT, oldEvent, event));
      }
    }
    return event;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event basicGetEvent()
  {
    return event;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEvent(Event newEvent)
  {
    Event oldEvent = event;
    event = newEvent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDSLPackage.TRANSITIONS__EVENT, oldEvent, event));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rate getEventrates()
  {
    if (eventrates != null && eventrates.eIsProxy())
    {
      InternalEObject oldEventrates = (InternalEObject)eventrates;
      eventrates = (Rate)eResolveProxy(oldEventrates);
      if (eventrates != oldEventrates)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDSLPackage.TRANSITIONS__EVENTRATES, oldEventrates, eventrates));
      }
    }
    return eventrates;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Rate basicGetEventrates()
  {
    return eventrates;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEventrates(Rate newEventrates)
  {
    Rate oldEventrates = eventrates;
    eventrates = newEventrates;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDSLPackage.TRANSITIONS__EVENTRATES, oldEventrates, eventrates));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public State getTarget()
  {
    if (target != null && target.eIsProxy())
    {
      InternalEObject oldTarget = (InternalEObject)target;
      target = (State)eResolveProxy(oldTarget);
      if (target != oldTarget)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDSLPackage.TRANSITIONS__TARGET, oldTarget, target));
      }
    }
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public State basicGetTarget()
  {
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTarget(State newTarget)
  {
    State oldTarget = target;
    target = newTarget;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDSLPackage.TRANSITIONS__TARGET, oldTarget, target));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDSLPackage.TRANSITIONS__EVENT:
        if (resolve) return getEvent();
        return basicGetEvent();
      case MyDSLPackage.TRANSITIONS__EVENTRATES:
        if (resolve) return getEventrates();
        return basicGetEventrates();
      case MyDSLPackage.TRANSITIONS__TARGET:
        if (resolve) return getTarget();
        return basicGetTarget();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDSLPackage.TRANSITIONS__EVENT:
        setEvent((Event)newValue);
        return;
      case MyDSLPackage.TRANSITIONS__EVENTRATES:
        setEventrates((Rate)newValue);
        return;
      case MyDSLPackage.TRANSITIONS__TARGET:
        setTarget((State)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDSLPackage.TRANSITIONS__EVENT:
        setEvent((Event)null);
        return;
      case MyDSLPackage.TRANSITIONS__EVENTRATES:
        setEventrates((Rate)null);
        return;
      case MyDSLPackage.TRANSITIONS__TARGET:
        setTarget((State)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDSLPackage.TRANSITIONS__EVENT:
        return event != null;
      case MyDSLPackage.TRANSITIONS__EVENTRATES:
        return eventrates != null;
      case MyDSLPackage.TRANSITIONS__TARGET:
        return target != null;
    }
    return super.eIsSet(featureID);
  }

} //TransitionsImpl
