/*
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDSLScopeProvider extends DelegatingScopeProvider {
}
