/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosarch.csdesign.ide;

import com.google.inject.Injector;
import org.xtext.sosarch.csdesign.MyDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyDslIdeSetup extends MyDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from MyDslRuntimeModule to Module"
      + "\nType mismatch: cannot convert from MyDslIdeModule to Module");
  }
}
