/**
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine.scoping;

import org.xtext.behavior.withstatemachine.scoping.AbstractMyDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MyDSLScopeProvider extends AbstractMyDSLScopeProvider {
}
