/**
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine.validation;

import org.xtext.behavior.withstatemachine.validation.AbstractMyDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyDSLValidator extends AbstractMyDSLValidator {
}
