/**
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine;

import org.xtext.behavior.withstatemachine.AbstractMyDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDSLRuntimeModule extends AbstractMyDSLRuntimeModule {
}
