/**
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine;

import org.xtext.behavior.withstatemachine.MyDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDSLStandaloneSetup extends MyDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new MyDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
