/*
 * generated by Xtext 2.19.0
 */
package org.xtext.behavior.withstatemachine


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyDSLStandaloneSetup extends MyDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MyDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
